// Code generated by componentgen. DO NOT EDIT.
package component

// Wearable represents the minecraft:wearable component.
type Wearable struct {
	Slot                SlotArmor
	Protection          int32
	HidesPlayerLocation bool
	Dispensable         bool
}

func (w Wearable) ComponentName() string { return "minecraft:wearable" }

func (w Wearable) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["slot"] = w.Slot
	data["protection"] = w.Protection
	data["hides_player_location"] = w.HidesPlayerLocation
	data["dispensable"] = w.Dispensable
	return data, nil
}

// SlotArmor is a named string type for the "minecraft:wearable" slot values.
type SlotArmor string

const (
	SlotArmorHead  SlotArmor = "slot.armor.head"
	SlotArmorChest SlotArmor = "slot.armor.chest"
	SlotArmorLegs  SlotArmor = "slot.armor.legs"
	SlotArmorFeet  SlotArmor = "slot.armor.feet"
)

// Food represents the minecraft:food component.
type Food struct {
	Nutrition          int32
	SaturationModifier float32
	CanAlwaysEat       bool
	UsingConvertsTo    string
	OnUseAction        int32
	CooldownTime       int32
	CooldownType       string
	Effects            []FoodEffect
	RemoveEffects      []int32
}

func (f Food) ComponentName() string { return "minecraft:food" }

func (f Food) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["nutrition"] = f.Nutrition
	data["saturation_modifier"] = f.SaturationModifier
	data["can_always_eat"] = f.CanAlwaysEat
	if f.UsingConvertsTo != "" {
		data["using_converts_to"] = f.UsingConvertsTo
	}
	if f.OnUseAction != 0 {
		data["on_use_action"] = f.OnUseAction
	}
	if f.CooldownTime != 0 {
		data["cooldown_time"] = f.CooldownTime
	}
	if f.CooldownType != "" {
		data["cooldown_type"] = f.CooldownType
	}
	if len(f.Effects) > 0 {
		data["effects"] = encodeSlice(f.Effects, encodeFoodEffect)
	}
	if len(f.RemoveEffects) > 0 {
		data["remove_effects"] = scalarSlice(f.RemoveEffects)
	}
	return data, nil
}

// Durability represents the minecraft:durability component.
type Durability struct {
	MaxDurability int32
	DamageChance  [2]int32
}

func (d Durability) ComponentName() string { return "minecraft:durability" }

func (d Durability) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["max_durability"] = d.MaxDurability
	data["damage_chance"] = rangeIntData(d.DamageChance)
	return data, nil
}

// KineticWeapon represents the minecraft:kinetic_weapon component.
type KineticWeapon struct {
	CreativeReach       [2]float32
	DamageConditions    WeaponConditions
	DamageModifier      float32
	DamageMultiplier    float32
	Delay               int32
	DismountConditions  WeaponConditions
	HitboxMargin        float32
	KnockbackConditions WeaponConditions
	Reach               [2]float32
}

func (k KineticWeapon) ComponentName() string { return "minecraft:kinetic_weapon" }

func (k KineticWeapon) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["creative_reach"] = rangeData(k.CreativeReach)
	data["damage_conditions"] = encodeWeaponConditions(k.DamageConditions)
	data["damage_modifier"] = k.DamageModifier
	data["damage_multiplier"] = k.DamageMultiplier
	data["delay"] = k.Delay
	data["dismount_conditions"] = encodeWeaponConditions(k.DismountConditions)
	data["hitbox_margin"] = k.HitboxMargin
	data["knockback_conditions"] = encodeWeaponConditions(k.KnockbackConditions)
	data["reach"] = rangeData(k.Reach)
	return data, nil
}

// UseModifiers represents the minecraft:use_modifiers component.
type UseModifiers struct {
	MovementModifier float32
	UseDuration      float32
	EmitVibrations   bool
	StartSound       string
	StartUsing       string
}

func (u UseModifiers) ComponentName() string { return "minecraft:use_modifiers" }

func (u UseModifiers) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["movement_modifier"] = u.MovementModifier
	data["use_duration"] = u.UseDuration
	data["emit_vibrations"] = u.EmitVibrations
	if u.StartSound != "" {
		data["start_sound"] = u.StartSound
	}
	if u.StartUsing != "" {
		data["start_using"] = u.StartUsing
	}
	return data, nil
}

// StorageItem represents the minecraft:storage_item component.
type StorageItem struct {
	AllowNestedStorageItems bool
	AllowedItems            []string
	BannedItems             []string
	MaxSlots                int32
}

func (s StorageItem) ComponentName() string { return "minecraft:storage_item" }

func (s StorageItem) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["allow_nested_storage_items"] = s.AllowNestedStorageItems
	data["allowed_items"] = stringSlice(s.AllowedItems)
	data["banned_items"] = bannedItemsData(s.BannedItems)
	data["max_slots"] = s.MaxSlots
	return data, nil
}

// Shooter represents the minecraft:shooter component.
type Shooter struct {
	Ammunition               []Ammunition
	ChargeOnDraw             bool
	MaxDrawDuration          float32
	ScalePowerByDrawDuration bool
}

func (s Shooter) ComponentName() string { return "minecraft:shooter" }

func (s Shooter) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["ammunition"] = encodeSlice(s.Ammunition, encodeAmmunition)
	data["charge_on_draw"] = s.ChargeOnDraw
	data["max_draw_duration"] = s.MaxDrawDuration
	data["scale_power_by_draw_duration"] = s.ScalePowerByDrawDuration
	return data, nil
}

// Projectile represents the minecraft:projectile component.
type Projectile struct {
	MinimumCriticalPower float32
	ProjectileEntity     string
}

func (p Projectile) ComponentName() string { return "minecraft:projectile" }

func (p Projectile) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["minimum_critical_power"] = p.MinimumCriticalPower
	data["projectile_entity"] = p.ProjectileEntity
	return data, nil
}

// Throwable represents the minecraft:throwable component.
type Throwable struct {
	DoSwingAnimation         bool
	LaunchPowerScale         float32
	MaxDrawDuration          float32
	MaxLaunchPower           float32
	MinDrawDuration          float32
	ScalePowerByDrawDuration bool
}

func (t Throwable) ComponentName() string { return "minecraft:throwable" }

func (t Throwable) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["do_swing_animation"] = t.DoSwingAnimation
	if t.LaunchPowerScale != 0 {
		data["launch_power_scale"] = t.LaunchPowerScale
	}
	if t.MaxDrawDuration != 0 {
		data["max_draw_duration"] = t.MaxDrawDuration
	}
	if t.MaxLaunchPower != 0 {
		data["max_launch_power"] = t.MaxLaunchPower
	}
	if t.MinDrawDuration != 0 {
		data["min_draw_duration"] = t.MinDrawDuration
	}
	if t.ScalePowerByDrawDuration != false {
		data["scale_power_by_draw_duration"] = t.ScalePowerByDrawDuration
	}
	return data, nil
}

// Damage represents the minecraft:damage component.
type Damage struct {
	Value float32
}

func (d Damage) ComponentName() string { return "minecraft:damage" }

func (d Damage) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = d.Value
	return data, nil
}

// Cooldown represents the minecraft:cooldown component.
type Cooldown struct {
	Category string
	Duration float32
	Type     string
}

func (c Cooldown) ComponentName() string { return "minecraft:cooldown" }

func (c Cooldown) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["category"] = c.Category
	data["duration"] = c.Duration
	if c.Type != "" {
		data["type"] = c.Type
	}
	return data, nil
}

// Enchantable represents the minecraft:enchantable component.
type Enchantable struct {
	Slot  string
	Value int32
}

func (e Enchantable) ComponentName() string { return "minecraft:enchantable" }

func (e Enchantable) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["slot"] = e.Slot
	data["value"] = e.Value
	return data, nil
}

// Repairable represents the minecraft:repairable component.
type Repairable struct {
	RepairItems []RepairEntry
}

func (r Repairable) ComponentName() string { return "minecraft:repairable" }

func (r Repairable) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["repair_items"] = encodeSlice(r.RepairItems, encodeRepairEntry)
	return data, nil
}

// ItemTags represents the minecraft:item_tags component.
type ItemTags struct {
	Tags []string
}

func (i ItemTags) ComponentName() string { return "minecraft:item_tags" }

func (i ItemTags) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["tags"] = stringSlice(i.Tags)
	return data, nil
}

// Tags represents the minecraft:tags component.
type Tags struct {
	Tags []string
}

func (t Tags) ComponentName() string { return "minecraft:tags" }

func (t Tags) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["tags"] = stringSlice(t.Tags)
	return data, nil
}

// Seed represents the minecraft:seed component.
type Seed struct {
	CropResult             string
	PlantAt                []string
	PlantAtAnySolidSurface bool
	PlantAtFace            string
}

func (s Seed) ComponentName() string { return "minecraft:seed" }

func (s Seed) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["crop_result"] = s.CropResult
	data["plant_at"] = stringSlice(s.PlantAt)
	data["plant_at_any_solid_surface"] = s.PlantAtAnySolidSurface
	data["plant_at_face"] = s.PlantAtFace
	return data, nil
}

// Fuel represents the minecraft:fuel component.
type Fuel struct {
	Duration float32
}

func (f Fuel) ComponentName() string { return "minecraft:fuel" }

func (f Fuel) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["duration"] = f.Duration
	return data, nil
}

// FireResistant represents the minecraft:fire_resistant component.
type FireResistant struct {
	Value bool
}

func (f FireResistant) ComponentName() string { return "minecraft:fire_resistant" }

func (f FireResistant) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = f.Value
	return data, nil
}

// Glint represents the minecraft:glint component.
type Glint struct {
	Value bool
}

func (g Glint) ComponentName() string { return "minecraft:glint" }

func (g Glint) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = g.Value
	return data, nil
}

// SwingDuration represents the minecraft:swing_duration component.
type SwingDuration struct {
	Value float32
}

func (s SwingDuration) ComponentName() string { return "minecraft:swing_duration" }

func (s SwingDuration) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = s.Value
	return data, nil
}

// SwingSounds represents the minecraft:swing_sounds component.
type SwingSounds struct {
	AttackCriticalHit string
	AttackHit         string
	AttackMiss        string
}

func (s SwingSounds) ComponentName() string { return "minecraft:swing_sounds" }

func (s SwingSounds) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["attack_critical_hit"] = s.AttackCriticalHit
	data["attack_hit"] = s.AttackHit
	data["attack_miss"] = s.AttackMiss
	return data, nil
}

// PiercingWeapon represents the minecraft:piercing_weapon component.
type PiercingWeapon struct {
	CreativeReach [2]float32
	HitboxMargin  float32
	Reach         [2]float32
}

func (p PiercingWeapon) ComponentName() string { return "minecraft:piercing_weapon" }

func (p PiercingWeapon) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["creative_reach"] = rangeData(p.CreativeReach)
	data["hitbox_margin"] = p.HitboxMargin
	data["reach"] = rangeData(p.Reach)
	return data, nil
}

// Camera represents the minecraft:camera component.
type Camera struct {
	BlackBarsDuration    float32
	BlackBarsScreenRatio float32
	PictureDuration      float32
	ShutterDuration      float32
	ShutterScreenRatio   float32
	SlideAwayDuration    float32
	UseDuration          int32
}

func (c Camera) ComponentName() string { return "minecraft:camera" }

func (c Camera) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["black_bars_duration"] = c.BlackBarsDuration
	data["black_bars_screen_ratio"] = c.BlackBarsScreenRatio
	data["picture_duration"] = c.PictureDuration
	data["shutter_duration"] = c.ShutterDuration
	data["shutter_screen_ratio"] = c.ShutterScreenRatio
	data["slide_away_duration"] = c.SlideAwayDuration
	data["use_duration"] = c.UseDuration
	return data, nil
}

// Block represents the minecraft:block component.
type Block struct {
	Value string
}

func (b Block) ComponentName() string { return "minecraft:block" }

func (b Block) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = b.Value
	return data, nil
}

// BlockPlacer represents the minecraft:block_placer component.
type BlockPlacer struct {
	Block            string
	ReplaceBlockItem string
	AlignedPlacement bool
	UseOn            []string
}

func (b BlockPlacer) ComponentName() string { return "minecraft:block_placer" }

func (b BlockPlacer) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["block"] = b.Block
	data["replace_block_item"] = b.ReplaceBlockItem
	data["aligned_placement"] = b.AlignedPlacement
	if len(b.UseOn) > 0 {
		data["use_on"] = stringSlice(b.UseOn)
	}
	return data, nil
}

// Compostable represents the minecraft:compostable component.
type Compostable struct {
	CompostingChance int32
}

func (c Compostable) ComponentName() string { return "minecraft:compostable" }

func (c Compostable) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["composting_chance"] = c.CompostingChance
	return data, nil
}

// DamageAbsorption represents the minecraft:damage_absorption component.
type DamageAbsorption struct {
	AbsorbableCauses []string
}

func (d DamageAbsorption) ComponentName() string { return "minecraft:damage_absorption" }

func (d DamageAbsorption) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["absorbable_causes"] = stringSlice(d.AbsorbableCauses)
	return data, nil
}

// Digger represents the minecraft:digger component.
type Digger struct {
	DestroySpeeds []DestroySpeed
	UseEfficiency bool
}

func (d Digger) ComponentName() string { return "minecraft:digger" }

func (d Digger) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["destroy_speeds"] = encodeSlice(d.DestroySpeeds, encodeDestroySpeed)
	data["use_efficiency"] = d.UseEfficiency
	return data, nil
}

// DurabilitySensor represents the minecraft:durability_sensor component.
type DurabilitySensor struct {
	SoundEvent           string
	DurabilityThresholds []DurabilityThreshold
}

func (d DurabilitySensor) ComponentName() string { return "minecraft:durability_sensor" }

func (d DurabilitySensor) Encode() (map[string]any, error) {
	data := map[string]any{}
	if d.SoundEvent != "" {
		data["sound_event"] = d.SoundEvent
	}
	if len(d.DurabilityThresholds) > 0 {
		data["durability_thresholds"] = encodeSlice(d.DurabilityThresholds, encodeDurabilityThreshold)
	}
	return data, nil
}

// Dyeable represents the minecraft:dyeable component.
type Dyeable struct {
	DefaultColor [3]int32
}

func (d Dyeable) ComponentName() string { return "minecraft:dyeable" }

func (d Dyeable) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["default_color"] = list3Data(d.DefaultColor)
	return data, nil
}

// EntityPlacer represents the minecraft:entity_placer component.
type EntityPlacer struct {
	Entity     string
	UseOn      []string
	DispenseOn []string
}

func (e EntityPlacer) ComponentName() string { return "minecraft:entity_placer" }

func (e EntityPlacer) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["entity"] = e.Entity
	if len(e.UseOn) > 0 {
		data["use_on"] = stringSlice(e.UseOn)
	}
	if len(e.DispenseOn) > 0 {
		data["dispense_on"] = stringSlice(e.DispenseOn)
	}
	return data, nil
}

// HoverTextColor represents the minecraft:hover_text_color component.
type HoverTextColor struct {
	Value int32
}

func (h HoverTextColor) ComponentName() string { return "minecraft:hover_text_color" }

func (h HoverTextColor) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = h.Value
	return data, nil
}

// InteractButton represents the minecraft:interact_button component.
type InteractButton struct {
	Value string
}

func (i InteractButton) ComponentName() string { return "minecraft:interact_button" }

func (i InteractButton) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = i.Value
	return data, nil
}

// LiquidClipped represents the minecraft:liquid_clipped component.
type LiquidClipped struct {
	Value bool
}

func (l LiquidClipped) ComponentName() string { return "minecraft:liquid_clipped" }

func (l LiquidClipped) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = l.Value
	return data, nil
}

// Rarity represents the minecraft:rarity component.
type Rarity struct {
	Value string
}

func (r Rarity) ComponentName() string { return "minecraft:rarity" }

func (r Rarity) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = r.Value
	return data, nil
}

// Record represents the minecraft:record component.
type Record struct {
	ComparatorSignal int32
	Duration         float32
	SoundEvent       string
}

func (r Record) ComponentName() string { return "minecraft:record" }

func (r Record) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["comparator_signal"] = r.ComparatorSignal
	data["duration"] = r.Duration
	data["sound_event"] = r.SoundEvent
	return data, nil
}

// ShouldDespawn represents the minecraft:should_despawn component.
type ShouldDespawn struct {
	Value bool
}

func (s ShouldDespawn) ComponentName() string { return "minecraft:should_despawn" }

func (s ShouldDespawn) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["value"] = s.Value
	return data, nil
}

// BundleInteraction represents the minecraft:bundle_interaction component.
type BundleInteraction struct {
	NumViewableSlots int32
}

func (b BundleInteraction) ComponentName() string { return "minecraft:bundle_interaction" }

func (b BundleInteraction) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["num_viewable_slots"] = b.NumViewableSlots
	return data, nil
}

// StorageWeightLimit represents the minecraft:storage_weight_limit component.
type StorageWeightLimit struct {
	MaxWeightLimit int32
}

func (s StorageWeightLimit) ComponentName() string { return "minecraft:storage_weight_limit" }

func (s StorageWeightLimit) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["max_weight_limit"] = s.MaxWeightLimit
	return data, nil
}

// StorageWeightModifier represents the minecraft:storage_weight_modifier component.
type StorageWeightModifier struct {
	WeightInStorageItem int32
}

func (s StorageWeightModifier) ComponentName() string { return "minecraft:storage_weight_modifier" }

func (s StorageWeightModifier) Encode() (map[string]any, error) {
	data := map[string]any{}
	data["weight_in_storage_item"] = s.WeightInStorageItem
	return data, nil
}

// Ammunition represents a nested structure used by a component.
type Ammunition struct {
	Item            string
	SearchInventory bool
	UseInCreative   bool
	UseOffHand      bool
}

// DestroySpeed represents a nested structure used by a component.
type DestroySpeed struct {
	Block string
	Speed float32
}

// DurabilityThreshold represents a nested structure used by a component.
type DurabilityThreshold struct {
	Durability   int32
	ParticleType string
	SoundEvent   string
}

// FoodEffect represents a nested structure used by a component.
type FoodEffect struct {
	ID        int32
	Duration  int32
	Amplifier int32
	Chance    float32
	Name      string
}

// RepairEntry represents a nested structure used by a component.
type RepairEntry struct {
	Items        []RepairItemEntry
	RepairAmount int32
}

// RepairItemEntry represents a nested structure used by a component.
type RepairItemEntry struct {
	Name string
	Tags []string
}

// WeaponConditions represents a nested structure used by a component.
type WeaponConditions struct {
	MaxDuration      int32
	MinSpeed         float32
	MinRelativeSpeed float32
}

func encodeAmmunition(v Ammunition) map[string]any {
	data := map[string]any{}
	data["item"] = v.Item
	data["search_inventory"] = v.SearchInventory
	data["use_in_creative"] = v.UseInCreative
	data["use_offhand"] = v.UseOffHand
	return data
}

func encodeDestroySpeed(v DestroySpeed) map[string]any {
	data := map[string]any{}
	data["block"] = v.Block
	data["speed"] = v.Speed
	return data
}

func encodeDurabilityThreshold(v DurabilityThreshold) map[string]any {
	data := map[string]any{}
	data["durability"] = v.Durability
	if v.ParticleType != "" {
		data["particle_type"] = v.ParticleType
	}
	if v.SoundEvent != "" {
		data["sound_event"] = v.SoundEvent
	}
	return data
}

func encodeFoodEffect(v FoodEffect) map[string]any {
	data := map[string]any{}
	data["id"] = v.ID
	data["duration"] = v.Duration
	data["amplifier"] = v.Amplifier
	data["chance"] = v.Chance
	if v.Name != "" {
		data["name"] = v.Name
	}
	return data
}

func encodeRepairEntry(v RepairEntry) map[string]any {
	data := map[string]any{}
	data["items"] = encodeNameOrTags(v.Items)
	data["repair_amount"] = v.RepairAmount
	return data
}

func encodeWeaponConditions(v WeaponConditions) map[string]any {
	data := map[string]any{}
	data["max_duration"] = v.MaxDuration
	data["min_speed"] = v.MinSpeed
	data["min_relative_speed"] = v.MinRelativeSpeed
	return data
}

func stringSlice(s []string) []any {
	r := make([]any, len(s))
	for i, v := range s {
		r[i] = v
	}
	return r
}

func scalarSlice[T any](s []T) []any {
	r := make([]any, len(s))
	for i, v := range s {
		r[i] = v
	}
	return r
}

func encodeSlice[V any](vs []V, enc func(V) map[string]any) []any {
	r := make([]any, len(vs))
	for i, v := range vs {
		r[i] = enc(v)
	}
	return r
}

func rangeData(r [2]float32) map[string]any {
	return map[string]any{"min": r[0], "max": r[1]}
}

func rangeIntData(r [2]int32) map[string]any {
	return map[string]any{"min": r[0], "max": r[1]}
}

func list3Data(c [3]int32) []any {
	return []any{c[0], c[1], c[2]}
}

func bannedItemsData(items []string) []any {
	banned := make([]any, len(items))
	for i, b := range items {
		banned[i] = map[string]any{"name": b}
	}
	return banned
}

func encodeNameOrTags(items []RepairItemEntry) []any {
	r := make([]any, len(items))
	for i, item := range items {
		if item.Name != "" {
			r[i] = map[string]any{"name": item.Name}
		} else {
			r[i] = map[string]any{"tags": stringSlice(item.Tags)}
		}
	}
	return r
}
