// Code generated by componentgen. DO NOT EDIT.
package component

import "fmt"

// ValidationRules contains cross-component validation rules derived from BDS.
var ValidationRules = map[string][]string{
	"minecraft:kinetic_weapon":     {"minecraft:use_modifiers"},
	"minecraft:bundle_interaction": {"minecraft:storage_item"},
	"minecraft:shooter":            {"minecraft:use_modifiers"},
}

// ValidateComponents checks cross-component constraints.
func ValidateComponents(components map[string]any) error {
	// kinetic_weapon requires use_modifiers
	if _, ok := components["minecraft:kinetic_weapon"]; ok {
		if _, ok := components["minecraft:use_modifiers"]; !ok {
			return fmt.Errorf("minecraft:kinetic_weapon requires minecraft:use_modifiers component")
		}
	}

	// bundle_interaction requires storage_item
	if _, ok := components["minecraft:bundle_interaction"]; ok {
		if _, ok := components["minecraft:storage_item"]; !ok {
			return fmt.Errorf("minecraft:bundle_interaction requires minecraft:storage_item component")
		}
	}

	// shooter requires use_modifiers with non-zero use_duration
	if _, ok := components["minecraft:shooter"]; ok {
		if um, ok := components["minecraft:use_modifiers"].(map[string]any); ok {
			if ud, ok := um["use_duration"].(float32); !ok || ud == 0 {
				return fmt.Errorf("minecraft:shooter requires non-zero use_duration in minecraft:use_modifiers")
			}
		} else {
			return fmt.Errorf("minecraft:shooter requires minecraft:use_modifiers component with non-zero use_duration")
		}
	}

	return nil
}
