package block

const (
	hashAir uint64 = iota
	hashAncientDebris
	hashBarrier
	hashBasalt
	hashBeacon
	hashBedrock
	hashBeetroot
	hashBlueIce
	hashBricks
	hashBoneBlock
	hashCake
	hashCarpet
	hashCarrot
	hashChest
	hashClay
	hashCoalBlock
	hashCoalOre
	hashCobblestone
	hashCocoa
	hashConcrete
	hashConcretePowder
	hashCoral
	hashCoralBlock
	hashCryingObsidian
	hashDiamondBlock
	hashDiamondOre
	hashDirt
	hashDoor
	hashDragonEgg
	hashEmeraldBlock
	hashEmeraldOre
	hashEndBricks
	hashEndBrickStairs
	hashEndStone
	hashFarmland
	hashFire
	hashGildedBlackstone
	hashGlass
	hashGlazedTerracotta
	hashGlowstone
	hashGoldBlock
	hashGoldOre
	hashGrass
	hashGrassPath
	hashGravel
	hashFenceGate
	hashInvisibleBedrock
	hashIronBars
	hashIronBlock
	hashIronOre
	hashKelp
	hashLantern
	hashLapisBlock
	hashLapisOre
	hashLava
	hashLeaves
	hashLight
	hashLitPumpkin
	hashLog
	hashMelon
	hashMelonStem
	hashNetherBrickFence
	hashNetherGoldOre
	hashNetheriteBlock
	hashNetherrack
	hashNetherWart
	hashNoteblock
	hashObsidian
	hashPlanks
	hashPotato
	hashPumpkin
	hashPumpkinStem
	hashQuartzOre
	hashQuartz
	hashChiseledQuartz
	hashQuartzPillar
	hashQuartzBricks
	hashSand
	hashSandstone
	hashShroomlight
	hashSeaLantern
	hashSoulSand
	hashSoulSoil
	hashSponge
	hashStainedTerracotta
	hashStone
	hashTorch
	hashGranite
	hashDiorite
	hashAndesite
	hashTerracotta
	hashTrapdoor
	hashWater
	hashWoodFence
	hashWoodSlab
	hashWoodStairs
	hashWool
	hashGlassPane
	hashStainedGlassPane
	hashStainedGlass
	hashWheat
)
