package block

const (
	hashAir uint64 = iota
	hashAncientDebris
	hashBeacon
	hashBedrock
	hashBoneBlock
	hashCarpet
	hashChest
	hashClay
	hashCoalBlock
	hashCoalOre
	hashCobblestone
	hashCocoa
	hashConcrete
	hashCoral
	hashCoralBlock
	hashDiamondBlock
	hashDiamondOre
	hashDirt
	hashDoor
	hashEmeraldBlock
	hashEmeraldOre
	hashEndBricks
	hashEndBrickStairs
	hashEndStone
	hashGlass
	hashGlazedTerracotta
	hashGlowstone
	hashGoldBlock
	hashGoldOre
	hashGrass
	hashGrassPath
	hashFenceGate
	hashIronBlock
	hashIronOre
	hashKelp
	hashLantern
	hashLapisBlock
	hashLapisOre
	hashLava
	hashLeaves
	hashLight
	hashLitPumpkin
	hashLog
	hashNetherGoldOre
	hashNetheriteBlock
	hashNetherrack
	hashObsidian
	hashPlanks
	hashPumpkin
	hashSponge
	hashStainedTerracotta
	hashStone
	hashSmoothStoneSlab
	hashSandstoneSlab
	hashWoodenSlab
	hashCobblestoneSlab
	hashBrickSlab
	hashStoneBrickSlab
	hashQuartzSlab
	hashNetherBrickSlab
	hashRedSandstoneSlab
	hashPurpurSlab
	hashPrismarineRoughSlab
	hashPrismarineDarkSlab
	hashPrismarineBrickSlab
	hashMossyCobblestoneSlab
	hashSmoothSandstoneSlab
	hashRedNetherBrickSlab
	hashEndStoneBrickSlab
	hashSmoothRedSandstoneSlab
	hashPolishedAndesiteSlab
	hashAndesiteSlab
	hashDioriteSlab
	hashPolishedDioriteSlab
	hashGraniteSlab
	hashPolishedGraniteSlab
	hashMossyStoneBrickSlab
	hashSmoothQuartzSlab
	hashStoneSlab
	hashCutSandstoneSlab
	hashCutRedSandstoneSlab
	hashBlackstoneSlab
	hashPolishedBlackstoneSlab
	hashPolishedBlackstoneBrickSlab
	hashGranite
	hashDiorite
	hashAndesite
	hashTerracotta
	hashTrapdoor
	hashWater
	hashWoodSlab
	hashWoodStairs
	hashWool
	hashGlassPane
	hashStainedGlassPane
	hashStainedGlass
)
