package block

// Stone ...
type Stone struct{}

// Name ...
func (l Stone) Name() string { return "Stone" }

// Granite ...
type Granite struct{}

// Name ...
func (l Granite) Name() string { return "Granite" }

// PolishedGranite ...
type PolishedGranite struct{}

// Name ...
func (l PolishedGranite) Name() string { return "Polished Granite" }

// Diorite ...
type Diorite struct{}

// Name ...
func (l Diorite) Name() string { return "Diorite" }

// PolishedDiorite ...
type PolishedDiorite struct{}

// Name ...
func (l PolishedDiorite) Name() string { return "Polished Diorite" }

// Andesite ...
type Andesite struct{}

// Name ...
func (l Andesite) Name() string { return "Andesite" }

// PolishedAndesite ...
type PolishedAndesite struct{}

// Name ...
func (l PolishedAndesite) Name() string { return "Polished Andesite" }
