// Code generated by .github/workflows/push.yml; DO NOT EDIT

package session

// enchantNames are names translated to the 'Standard Galactic Alphabet' client-side. The names generally have no meaning
// on the vanilla server implementation, so we can sneak some easter eggs in here without anyone noticing.
var enchantNames = []string{"abimek", "aericio", "aimjel", "alvin0319", "andreas hgk", "atm85", "blackjack200", "da pig guy", "deniel world", "didntpot", "eminarican", "endermanbugzjfc", "flonja", "hashim the arab", "hochbaum", "hyper flare mc", "im da real ani", "imlighty", "its zodia x", "ivan craft623", "javier leon9966", "just tal develops", "liatoast", "mmm545", "mohamed587100", "neutronic mc", "nonono697", "provsalt", "restart fu", "riccskn", "robertdudaa", "royal mcpe", "sallypemdas", "sandertv", "sculas", "sqmatheus", "ssaini123456", "t14 raptor", "tadhunt", "thunder33345", "tristanmorgan", "twisted asylum mc", "unickorn", "unknown ore", "uramnoil", "wqrro", "x natsuri", "x4caa", "xd-pro"}
