// Code generated by .github/workflows/push.yml; DO NOT EDIT

package session

// enchantNames are names translated to the 'Standard Galactic Alphabet' client-side. The names generally have no meaning
// on the vanilla server implementation, so we can sneak some easter eggs in here without anyone noticing.
var enchantNames = []string{"aericio", "andreas hgk", "da pig guy", "deniel world", "endermanbugzjfc", "flonja", "im da real ani", "just tal develops", "liatoast", "mohamed587100", "neutronic mc", "prim69", "restart fu", "sallypemdas", "sandertv", "t14 raptor", "thunder33345", "twisted asylum mc", "unickorn", "unknown ore", "aimjel", "eminarican", "hochbaum", "mmm545", "nonono697", "provsalt", "robertdudaa", "sa111n111", "tristanmorgan", "varun-balani"}
