// Code generated by .github/workflows/push.yml; DO NOT EDIT

package session

var enchantNames = []string{"sandertv", "t14 raptor", "just tal develops", "da pig guy", "sa111n111", "andreas hgk", "twisted asylum mc", "prim69", "mmm545", "restart fu", "tristanmorgan", "endermanbugzjfc", "im da real ani", "provsalt", "hochbaum", "unickorn", "unknown ore", "aimjel", "deniel world", "nonono697", "thunder33345", "aericio", "mohamed587100", "eminarican", "heisenburger69", "liatoast", "neutronic mc", "robertdudaa", "sallypemdas", "sculas"}
