// Code generated by cmd/blockaccessor; DO NOT EDIT.

package block

import (
	"github.com/df-mc/dragonfly/server/block/cube"
	"github.com/df-mc/dragonfly/server/item"
	"github.com/df-mc/dragonfly/server/world"
)

// HasFacing represents a block with a horizontal facing direction. Blocks that face any of the six
// block faces (such as torches, levers and hoppers) or that use an attachment do not implement it.
type HasFacing interface {
	world.Block
	FacingDirection() cube.Direction
	WithFacing(facing cube.Direction) world.Block
}

// HasAxis represents a block oriented along one of the three axes, such as logs and pillars.
type HasAxis interface {
	world.Block
	PillarAxis() cube.Axis
	WithAxis(axis cube.Axis) world.Block
}

// HasColour represents a block that comes in the sixteen dye colours, such as wool and concrete. On
// some blocks, such as beds and banners, the colour is stored as block entity data rather than in the
// encoded block state.
type HasColour interface {
	world.Block
	DyeColour() item.Colour
	WithColour(colour item.Colour) world.Block
}

// FacingDirection returns the horizontal direction the block faces.
func (b Anvil) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Anvil) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Bed) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Bed) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b BlastFurnace) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b BlastFurnace) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Campfire) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Campfire) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Chest) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Chest) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b CocoaBean) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b CocoaBean) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b CopperDoor) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b CopperDoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b CopperGolemStatue) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b CopperGolemStatue) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b CopperTrapdoor) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b CopperTrapdoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b DecoratedPot) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b DecoratedPot) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b EnderChest) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b EnderChest) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Furnace) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Furnace) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b GlazedTerracotta) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b GlazedTerracotta) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Grindstone) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Grindstone) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Ladder) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Ladder) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Lectern) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Lectern) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b LitPumpkin) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b LitPumpkin) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Loom) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Loom) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b PinkPetals) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b PinkPetals) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Pumpkin) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Pumpkin) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Smoker) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Smoker) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Stairs) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Stairs) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b Stonecutter) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Stonecutter) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b WoodDoor) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b WoodDoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b WoodFenceGate) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b WoodFenceGate) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// FacingDirection returns the horizontal direction the block faces.
func (b WoodTrapdoor) FacingDirection() cube.Direction {
	return b.Facing
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b WoodTrapdoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b BambooBlock) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b BambooBlock) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b Basalt) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Basalt) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b Bone) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Bone) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b CopperChain) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b CopperChain) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b Deepslate) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Deepslate) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b Froglight) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Froglight) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b HayBale) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b HayBale) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b InfestedDeepslate) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b InfestedDeepslate) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b IronChain) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b IronChain) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b Log) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Log) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b MuddyMangroveRoots) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b MuddyMangroveRoots) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b PurpurPillar) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b PurpurPillar) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b QuartzPillar) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b QuartzPillar) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// PillarAxis returns the axis the block is oriented along.
func (b Wood) PillarAxis() cube.Axis {
	return b.Axis
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Wood) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// DyeColour returns the dye colour of the block.
func (b Banner) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b Banner) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b Bed) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b Bed) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b Carpet) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b Carpet) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b Concrete) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b Concrete) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b ConcretePowder) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b ConcretePowder) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b GlazedTerracotta) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b GlazedTerracotta) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b StainedGlass) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b StainedGlass) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b StainedGlassPane) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b StainedGlassPane) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b StainedTerracotta) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b StainedTerracotta) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// DyeColour returns the dye colour of the block.
func (b Wool) DyeColour() item.Colour {
	return b.Colour
}

// WithColour returns a copy of the block with its colour set to colour.
func (b Wool) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}
