package block

import (
	"github.com/df-mc/dragonfly/server/block/cube"
	"github.com/df-mc/dragonfly/server/block/model"
	"github.com/df-mc/dragonfly/server/item"
	"github.com/df-mc/dragonfly/server/world"
	"github.com/go-gl/mathgl/mgl64"
)

// SculkVein is a block found in the deep dark or generated by sculk catalysts.
type SculkVein struct {
	replaceable
	transparent
	empty
	sourceWaterDisplacer

	// North, East, South, West, Up, Down represent the faces the vein is attached to.
	North, East, South, West, Up, Down bool
}

// BreakInfo ...
func (s SculkVein) BreakInfo() BreakInfo {
	return newBreakInfo(0.2, alwaysHarvestable, hoeEffective, func(t item.Tool, enchantments []item.Enchantment) []item.Stack {
		if hasSilkTouch(enchantments) {
			return []item.Stack{item.NewStack(s, 1)}
		}
		return nil
	}).withXPDropRange(1, 1).withBlastResistance(1)
}

// EncodeItem ...
func (s SculkVein) EncodeItem() (name string, meta int16) {
	return "minecraft:sculk_vein", 0
}

// EncodeBlock maps the booleans to the "multi_face_direction_bits" property.
func (s SculkVein) EncodeBlock() (name string, properties map[string]any) {
	var bits int32
	if s.Down {
		bits |= 1
	}
	if s.Up {
		bits |= 2
	}
	if s.South {
		bits |= 4
	}
	if s.West {
		bits |= 8
	}
	if s.North {
		bits |= 16
	}
	if s.East {
		bits |= 32
	}

	return "minecraft:sculk_vein", map[string]any{"multi_face_direction_bits": bits}
}

// UseOnBlock allows placing the vein on any solid face.
func (s SculkVein) UseOnBlock(pos cube.Pos, face cube.Face, _ mgl64.Vec3, tx *world.Tx, user item.User, ctx *item.UseContext) bool {
	if _, ok := tx.Block(pos).Model().(model.Solid); !ok {
		return false
	}
	pos, face, used := firstReplaceable(tx, pos, face, s)
	if !used {
		return false
	}
	if _, ok := tx.Block(pos).(SculkVein); ok {
		return false
	}

	s = s.withFace(face.Opposite())
	place(tx, pos, s, user, ctx)
	return placed(ctx)
}

func (s SculkVein) withFace(f cube.Face) SculkVein {
	switch f {
	case cube.FaceUp:
		s.Up = true
	case cube.FaceDown:
		s.Down = true
	case cube.FaceNorth:
		s.North = true
	case cube.FaceSouth:
		s.South = true
	case cube.FaceWest:
		s.West = true
	case cube.FaceEast:
		s.East = true
	}
	return s
}

// allSculkVeins generates all 64 possible states (2^6).
func allSculkVeins() (b []world.Block) {
	for i := 0; i < 64; i++ {
		b = append(b, SculkVein{
			Down:  i&1 != 0,
			Up:    i&2 != 0,
			South: i&4 != 0,
			West:  i&8 != 0,
			North: i&16 != 0,
			East:  i&32 != 0,
		})
	}
	return
}
