package block

import (
	"github.com/df-mc/dragonfly/server/block/cube"
	"github.com/df-mc/dragonfly/server/item"
	"github.com/df-mc/dragonfly/server/item/enchantment"
	"github.com/df-mc/dragonfly/server/world"
	"github.com/df-mc/dragonfly/server/world/sound"
	"github.com/go-gl/mathgl/mgl64"
)

// SculkVein is a block found in the deep dark or generated by sculk catalysts.
type SculkVein struct {
	replaceable
	transparent
	empty
	sourceWaterDisplacer

	// North, East, South, West, Up, Down represent the faces the vein is attached to.
	North, East, South, West, Up, Down bool
}

// BreakInfo returns the break properties, dropping an item for every face if silk touched.
func (s SculkVein) BreakInfo() BreakInfo {
	return newBreakInfo(0.2, alwaysHarvestable, hoeEffective, func(t item.Tool, enchantments []item.Enchantment) []item.Stack {
		for _, ench := range enchantments {
			if ench.Type() == enchantment.SilkTouch {
				// Calculate active faces to determine the drop amount.
				count := 0
				if s.North {
					count++
				}
				if s.East {
					count++
				}
				if s.South {
					count++
				}
				if s.West {
					count++
				}
				if s.Up {
					count++
				}
				if s.Down {
					count++
				}

				// Drop the 'clean' version of the block (all faces false) with the count.
				return []item.Stack{item.NewStack(SculkVein{}, count)}
			}
		}
		return nil
	})
}

// EncodeItem ...
func (s SculkVein) EncodeItem() (name string, meta int16) {
	return "minecraft:sculk_vein", 0
}

// EncodeBlock maps the booleans to the "multi_face_direction_bits" property.
func (s SculkVein) EncodeBlock() (name string, properties map[string]any) {
	var bits int32
	if s.Down {
		bits |= 1
	}
	if s.Up {
		bits |= 2
	}
	if s.South {
		bits |= 4
	}
	if s.West {
		bits |= 8
	}
	if s.North {
		bits |= 16
	}
	if s.East {
		bits |= 32
	}

	return "minecraft:sculk_vein", map[string]any{"multi_face_direction_bits": bits}
}

func (s SculkVein) UseOnBlock(pos cube.Pos, face cube.Face, _ mgl64.Vec3, tx *world.Tx, user item.User, ctx *item.UseContext) bool {
	clickedBlock := tx.Block(pos)
	targetFace := face.Opposite()

	// 1. If we clicked an existing vein, try to add a face to IT.
	if existing, ok := clickedBlock.(SculkVein); ok {
		// First try the specific face clicked.
		if !existing.hasFace(targetFace) {
			if s.attemptMerge(pos, existing, targetFace, tx, ctx) {
				return true
			}
		}
		// Vanilla Logic: If clicking an occupied face, try to find ANY other
		// available face in this same block that has a solid support.
		if s.attemptMergeAny(pos, existing, tx, ctx) {
			return true
		}

		// If the current block is "full" for all available supports,
		// move to the air block next to it (wrap-around).
		pos = pos.Side(face)
	}

	// 2. Resolve position for a brand new block or wrap-around.
	actualPos, actualFace, used := firstReplaceable(tx, pos, face, s)
	if !used {
		return false
	}

	targetBlock := tx.Block(actualPos)
	newTargetFace := actualFace.Opposite()

	// 3. Merge if we landed on another vein.
	if existing, ok := targetBlock.(SculkVein); ok {
		if s.attemptMerge(actualPos, existing, newTargetFace, tx, ctx) {
			return true
		}
		return s.attemptMergeAny(actualPos, existing, tx, ctx)
	}

	// 4. Place a new block.
	supportPos := actualPos.Side(newTargetFace)
	if !tx.Block(supportPos).Model().FaceSolid(supportPos, actualFace, tx) {
		return false
	}

	newVein := SculkVein{}.WithFace(newTargetFace)
	place(tx, actualPos, newVein, user, ctx)
	return placed(ctx)
}

// attemptMergeAny searches all faces of the current block to find a valid
// empty face with a solid support block behind it.
func (s SculkVein) attemptMergeAny(pos cube.Pos, existing SculkVein, tx *world.Tx, ctx *item.UseContext) bool {
	for _, f := range cube.Faces() {
		if !existing.hasFace(f) {
			supportPos := pos.Side(f)
			// Check if the neighbor block is solid on the face touching us.
			if tx.Block(supportPos).Model().FaceSolid(supportPos, f.Opposite(), tx) {
				if s.attemptMerge(pos, existing, f, tx, ctx) {
					return true
				}
			}
		}
	}
	return false
}

// hasFace is a helper to check if a specific face is already active.
func (s SculkVein) hasFace(f cube.Face) bool {
	switch f {
	case cube.FaceUp:
		return s.Up
	case cube.FaceDown:
		return s.Down
	case cube.FaceNorth:
		return s.North
	case cube.FaceSouth:
		return s.South
	case cube.FaceWest:
		return s.West
	case cube.FaceEast:
		return s.East
	}
	return false
}

// attemptMerge handles adding a face and syncing inventory.
func (s SculkVein) attemptMerge(pos cube.Pos, existing SculkVein, face cube.Face, tx *world.Tx, ctx *item.UseContext) bool {
	newVein := existing.WithFace(face)
	if newVein == existing {
		return false
	}
	supportPos := pos.Side(face)
	if !tx.Block(supportPos).Model().FaceSolid(supportPos, face.Opposite(), tx) {
		return false
	}
	tx.SetBlock(pos, newVein, nil)
	tx.PlaySound(pos.Vec3Centre(), sound.BlockPlace{Block: SculkVein{}})
	ctx.SubtractFromCount(1)
	return true
}

// WithFace returns a SculkVein with the specified face set to true.
func (s SculkVein) WithFace(f cube.Face) SculkVein {
	switch f {
	case cube.FaceUp:
		s.Up = true
	case cube.FaceDown:
		s.Down = true
	case cube.FaceNorth:
		s.North = true
	case cube.FaceSouth:
		s.South = true
	case cube.FaceWest:
		s.West = true
	case cube.FaceEast:
		s.East = true
	}
	return s
}

// NeighbourUpdateTick checks if the sculk vein is still supported.
func (s SculkVein) NeighbourUpdateTick(pos, _ cube.Pos, tx *world.Tx) {
	changed := false
	checkSupport := func(face cube.Face, attached *bool) {
		if !*attached {
			return
		}
		supportPos := pos.Side(face)
		if !tx.Block(supportPos).Model().FaceSolid(supportPos, face.Opposite(), tx) {
			*attached = false
			changed = true
		}
	}

	checkSupport(cube.FaceDown, &s.Down)
	checkSupport(cube.FaceUp, &s.Up)
	checkSupport(cube.FaceNorth, &s.North)
	checkSupport(cube.FaceSouth, &s.South)
	checkSupport(cube.FaceWest, &s.West)
	checkSupport(cube.FaceEast, &s.East)

	if !changed {
		return
	}

	if !s.Down && !s.Up && !s.North && !s.South && !s.West && !s.East {
		breakBlock(s, pos, tx)
		return
	}

	tx.SetBlock(pos, s, nil)
}

// allSculkVeins generates all 64 possible states.
func allSculkVeins() (b []world.Block) {
	for i := 0; i < 64; i++ {
		b = append(b, SculkVein{
			Down:  i&1 != 0,
			Up:    i&2 != 0,
			South: i&4 != 0,
			West:  i&8 != 0,
			North: i&16 != 0,
			East:  i&32 != 0,
		})
	}
	return
}

// DecodeNBT decodes the NBT data from the world save. 
// It MUST have this exact signature to satisfy world.NBTer.
func (s SculkVein) DecodeNBT(data map[string]any) any {
	if v, ok := data["multi_face_direction_bits"]; ok {
		// multi_face_direction_bits is an int32 bitmask used by Bedrock.
		bits := v.(int32)
		s.Down = bits&1 != 0
		s.Up = bits&2 != 0
		s.South = bits&4 != 0
		s.West = bits&8 != 0
		s.North = bits&16 != 0
		s.East = bits&32 != 0
	}
	return s
}

// EncodeNBT encodes the SculkVein properties back into NBT for saving.
func (s SculkVein) EncodeNBT() map[string]any {
	var bits int32
	if s.Down { bits |= 1 }
	if s.Up { bits |= 2 }
	if s.South { bits |= 4 }
	if s.West { bits |= 8 }
	if s.North { bits |= 16 }
	if s.East { bits |= 32 }

	return map[string]any{
		"multi_face_direction_bits": bits,
	}
}
