package block

import (
	"github.com/df-mc/dragonfly/server/block/cube"
	"github.com/df-mc/dragonfly/server/block/model"
	"github.com/df-mc/dragonfly/server/item"
	"github.com/df-mc/dragonfly/server/item/enchantment"
	"github.com/df-mc/dragonfly/server/world"
	"github.com/go-gl/mathgl/mgl64"
)

// SculkVein is a block found in the deep dark or generated by sculk catalysts.
type SculkVein struct {
	replaceable
	transparent
	empty
	sourceWaterDisplacer

	// North, East, South, West, Up, Down represent the faces the vein is attached to.
	North, East, South, West, Up, Down bool
}

// BreakInfo returns the break properties, dropping an item for every face if silk touched.
func (s SculkVein) BreakInfo() BreakInfo {
	return newBreakInfo(0.2, alwaysHarvestable, hoeEffective, func(t item.Tool, enchantments []item.Enchantment) []item.Stack {
		for _, ench := range enchantments {
			if ench.Type() == enchantment.SilkTouch {
				// Calculate active faces to determine the drop amount.
				count := 0
				if s.North {
					count++
				}
				if s.East {
					count++
				}
				if s.South {
					count++
				}
				if s.West {
					count++
				}
				if s.Up {
					count++
				}
				if s.Down {
					count++
				}

				// Drop the 'clean' version of the block (all faces false) with the count.
				return []item.Stack{item.NewStack(SculkVein{}, count)}
			}
		}
		return nil
	})
}

// EncodeItem ...
func (s SculkVein) EncodeItem() (name string, meta int16) {
	return "minecraft:sculk_vein", 0
}

// EncodeBlock maps the booleans to the "multi_face_direction_bits" property.
func (s SculkVein) EncodeBlock() (name string, properties map[string]any) {
	var bits int32
	if s.Down {
		bits |= 1
	}
	if s.Up {
		bits |= 2
	}
	if s.South {
		bits |= 4
	}
	if s.West {
		bits |= 8
	}
	if s.North {
		bits |= 16
	}
	if s.East {
		bits |= 32
	}

	return "minecraft:sculk_vein", map[string]any{"multi_face_direction_bits": bits}
}

// UseOnBlock allows placing the vein on any solid face.
func (s SculkVein) UseOnBlock(pos cube.Pos, face cube.Face, _ mgl64.Vec3, tx *world.Tx, user item.User, ctx *item.UseContext) bool {
	if _, ok := tx.Block(pos).Model().(model.Solid); !ok {
		return false
	}
	pos, face, used := firstReplaceable(tx, pos, face, s)
	if !used {
		return false
	}

	// Handle merging with existing veins.
	if existing, ok := tx.Block(pos).(SculkVein); ok {
		newVein := existing.WithFace(face.Opposite())
		if newVein == existing {
			return false
		}
		place(tx, pos, newVein, user, ctx)
		return placed(ctx)
	}

	s = s.WithFace(face.Opposite())
	place(tx, pos, s, user, ctx)
	return placed(ctx)
}

// WithFace returns a SculkVein with the specified face set to true.
func (s SculkVein) WithFace(f cube.Face) SculkVein {
	switch f {
	case cube.FaceUp:
		s.Up = true
	case cube.FaceDown:
		s.Down = true
	case cube.FaceNorth:
		s.North = true
	case cube.FaceSouth:
		s.South = true
	case cube.FaceWest:
		s.West = true
	case cube.FaceEast:
		s.East = true
	}
	return s
}

// NeighbourUpdateTick checks if the sculk vein is still supported.
func (s SculkVein) NeighbourUpdateTick(pos, _ cube.Pos, tx *world.Tx) {
	changed := false
	checkSupport := func(face cube.Face, attached *bool) {
		if !*attached {
			return
		}
		supportPos := pos.Side(face)
		if !tx.Block(supportPos).Model().FaceSolid(supportPos, face.Opposite(), tx) {
			*attached = false
			changed = true
		}
	}

	checkSupport(cube.FaceDown, &s.Down)
	checkSupport(cube.FaceUp, &s.Up)
	checkSupport(cube.FaceNorth, &s.North)
	checkSupport(cube.FaceSouth, &s.South)
	checkSupport(cube.FaceWest, &s.West)
	checkSupport(cube.FaceEast, &s.East)

	if !changed {
		return
	}

	if !s.Down && !s.Up && !s.North && !s.South && !s.West && !s.East {
		breakBlock(s, pos, tx)
		return
	}

	tx.SetBlock(pos, s, nil)
}

// allSculkVeins generates all 64 possible states.
func allSculkVeins() (b []world.Block) {
	for i := 0; i < 64; i++ {
		b = append(b, SculkVein{
			Down:  i&1 != 0,
			Up:    i&2 != 0,
			South: i&4 != 0,
			West:  i&8 != 0,
			North: i&16 != 0,
			East:  i&32 != 0,
		})
	}
	return
}
