// Code generated by cmd/blocksetter; DO NOT EDIT.

package block

import (
	"github.com/df-mc/dragonfly/server/block/cube"
	"github.com/df-mc/dragonfly/server/item"
	"github.com/df-mc/dragonfly/server/world"
)

// HasFacing represents a block with a horizontal facing direction.
type HasFacing interface {
	world.Block
	WithFacing(facing cube.Direction) world.Block
}

// HasAxis represents a block with an axis.
type HasAxis interface {
	world.Block
	WithAxis(axis cube.Axis) world.Block
}

// HasColour represents a block with a colour.
type HasColour interface {
	world.Block
	WithColour(colour item.Colour) world.Block
}

// WithFacing returns the block with the facing set to facing.
func (b Anvil) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Bed) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b BlastFurnace) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Campfire) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Chest) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b CocoaBean) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b CopperDoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b CopperGolemStatue) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b CopperTrapdoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b DecoratedPot) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b EnderChest) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Furnace) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b GlazedTerracotta) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Grindstone) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Ladder) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Lectern) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b LitPumpkin) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Loom) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b PinkPetals) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Pumpkin) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Smoker) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Stairs) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b Stonecutter) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b WoodDoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b WoodFenceGate) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns the block with the facing set to facing.
func (b WoodTrapdoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b Basalt) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b Bone) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b CopperChain) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b Deepslate) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b Froglight) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b HayBale) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b IronChain) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b Log) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b MuddyMangroveRoots) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b PurpurPillar) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b QuartzPillar) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns the block with the axis set to axis.
func (b Wood) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithColour returns the block with the colour set to colour.
func (b Banner) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b Bed) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b Carpet) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b Concrete) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b ConcretePowder) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b GlazedTerracotta) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b StainedGlass) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b StainedGlassPane) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b StainedTerracotta) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}

// WithColour returns the block with the colour set to colour.
func (b Wool) WithColour(colour item.Colour) world.Block {
	b.Colour = colour
	return b
}
