// Code generated by cmd/blocksetter; DO NOT EDIT.

package block

import (
	"github.com/df-mc/dragonfly/server/block/cube"
	"github.com/df-mc/dragonfly/server/world"
)

// HasFacing represents a block with a horizontal facing direction. Blocks that face any of the six
// block faces (such as torches, levers and hoppers) or that use an attachment do not implement it.
type HasFacing interface {
	world.Block
	WithFacing(facing cube.Direction) world.Block
}

// HasAxis represents a block oriented along one of the three axes, such as logs and pillars.
type HasAxis interface {
	world.Block
	WithAxis(axis cube.Axis) world.Block
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Anvil) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Bed) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b BlastFurnace) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Campfire) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Chest) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b CocoaBean) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b CopperDoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b CopperGolemStatue) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b CopperTrapdoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b DecoratedPot) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b EnderChest) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Furnace) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b GlazedTerracotta) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Grindstone) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Ladder) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Lectern) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b LitPumpkin) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Loom) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b PinkPetals) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Pumpkin) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Smoker) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Stairs) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b Stonecutter) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b WoodDoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b WoodFenceGate) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithFacing returns a copy of the block with its facing set to facing. It does not update any
// other blocks that the block may be part of, such as the second half of a bed or door.
func (b WoodTrapdoor) WithFacing(facing cube.Direction) world.Block {
	b.Facing = facing
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Basalt) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Bone) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b CopperChain) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Deepslate) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Froglight) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b HayBale) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b IronChain) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Log) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b MuddyMangroveRoots) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b PurpurPillar) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b QuartzPillar) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}

// WithAxis returns a copy of the block with its axis set to axis.
func (b Wood) WithAxis(axis cube.Axis) world.Block {
	b.Axis = axis
	return b
}
