package generate

import (
	"bytes"
	"fmt"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"text/template"
	"unicode"

	"github.com/df-mc/dragonfly/cmd/generate/componentgen/parse"
)

type Generator struct {
	outputDir string
	schemas   map[string]parse.ComponentSchema
}

func NewGenerator(outputDir string, schemas map[string]parse.ComponentSchema) *Generator {
	// Filter to only known components that we have typed implementations for
	filtered := parse.FilterKnownComponents(schemas)
	return &Generator{
		outputDir: outputDir,
		schemas:   filtered,
	}
}

func (g *Generator) Generate() error {
	// Generate component type implementations (structs + ComponentName + Encode).
	if err := g.generateComponentImplementations(); err != nil {
		return fmt.Errorf("generate component implementations: %w", err)
	}

	// Generate constants.go
	if err := g.generateConstants(); err != nil {
		return fmt.Errorf("generate constants: %w", err)
	}

	// Generate validation.go
	if err := g.generateValidation(); err != nil {
		return fmt.Errorf("generate validation: %w", err)
	}

	return nil
}

func (g *Generator) generateConstants() error {
	tmpl := template.Must(template.New("constants").Parse(constantsTemplate))

	type Comp struct {
		Name       string
		ConstName  string
		StructName string
	}

	var components []Comp
	for _, spec := range manifest {
		components = append(components, Comp{
			Name:       spec.Name,
			ConstName:  componentNameToConst(spec.Name),
			StructName: spec.Struct,
		})
	}

	data := map[string]any{
		"Components": components,
	}

	path := filepath.Join(g.outputDir, "constants.go")
	return renderAndWrite(path, tmpl, data)
}

func (g *Generator) generateValidation() error {
	tmpl := template.Must(template.New("validation").Parse(validationTemplate))

	type Comp struct {
		Name       string
		StructName string
	}

	var components []Comp
	for _, name := range sortedSchemaNames(g.schemas) {
		structName := componentNameToStruct(name)
		components = append(components, Comp{
			Name:       name,
			StructName: structName,
		})
	}

	data := map[string]any{
		"Components": components,
	}

	path := filepath.Join(g.outputDir, "validation.go")
	return renderAndWrite(path, tmpl, data)
}

// renderAndWrite renders tmpl with data, gofmt-formats the result and writes it
// to path so generated files are always gofmt-clean.
func renderAndWrite(path string, tmpl *template.Template, data any) error {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	return writeFormattedFile(path, buf.Bytes())
}

// sortedSchemaNames returns the keys of schemas in sorted order so that generated
// files are deterministic regardless of Go map iteration order.
func sortedSchemaNames(schemas map[string]parse.ComponentSchema) []string {
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func componentNameToStruct(name string) string {
	// Remove "minecraft:" prefix
	name = strings.TrimPrefix(name, "minecraft:")
	// Convert snake_case to PascalCase
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func componentNameToConst(name string) string {
	// Remove "minecraft:" prefix and split parts.
	parts := strings.Split(strings.TrimPrefix(name, "minecraft:"), "_")

	parts = slices.DeleteFunc(parts, func(w string) bool { return w == "" }) // Remove empty parts

	for i, word := range parts {
		if len(word) == 0 {
			continue
		}
		// Capitalize first letter, lowercase the rest
		parts[i] = string(unicode.ToUpper(rune(word[0]))) + strings.ToLower(word[1:])
	}

	return strings.Join(parts, "")
}

const constantsTemplate = `// Code generated by componentgen. DO NOT EDIT.
package component

// Component name constants
const (
{{- range .Components }}
	Component{{ .ConstName }} = "{{ .Name }}"
{{- end }}
)
`

const validationTemplate = `// Code generated by componentgen. DO NOT EDIT.
package component

import "fmt"

// ValidationRules contains cross-component validation rules derived from BDS.
var ValidationRules = map[string][]string{
	"minecraft:kinetic_weapon": {"minecraft:use_modifiers"},
	"minecraft:bundle_interaction": {"minecraft:storage_item"},
	"minecraft:shooter": {"minecraft:use_modifiers"},
}

// ValidateComponents checks cross-component constraints.
func ValidateComponents(components map[string]any) error {
	// kinetic_weapon requires use_modifiers
	if _, ok := components["minecraft:kinetic_weapon"]; ok {
		if _, ok := components["minecraft:use_modifiers"]; !ok {
			return fmt.Errorf("minecraft:kinetic_weapon requires minecraft:use_modifiers component")
		}
	}

	// bundle_interaction requires storage_item
	if _, ok := components["minecraft:bundle_interaction"]; ok {
		if _, ok := components["minecraft:storage_item"]; !ok {
			return fmt.Errorf("minecraft:bundle_interaction requires minecraft:storage_item component")
		}
	}

	// shooter requires use_modifiers with non-zero use_duration
	if _, ok := components["minecraft:shooter"]; ok {
		if um, ok := components["minecraft:use_modifiers"].(map[string]any); ok {
			if ud, ok := um["use_duration"].(float32); !ok || ud == 0 {
				return fmt.Errorf("minecraft:shooter requires non-zero use_duration in minecraft:use_modifiers")
			}
		} else {
			return fmt.Errorf("minecraft:shooter requires minecraft:use_modifiers component with non-zero use_duration")
		}
	}

	return nil
}
`
