name: Compilar Dragonfly

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Limpiar y Actualizar Módulos
        run: |
          go mod tidy

      - name: Generar Hashes de Bloques
        run: |
          go generate ./server/block

      - name: Build Dragonfly
        run: |
          GOOS=linux GOARCH=arm64 go build -v -o dragonfly_server_arm64 main.go

      - name: Subir binario
        uses: actions/upload-artifact@v4
        with:
          name: dragonfly_server_bin
          path: dragonfly_server_arm64
