name: Deploy
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
  pull_request_target:
    types: [closed]

permissions:
  actions: read
  contents: read

jobs:

  deploy:
    name: Deploy
    if: >-
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0] != null
    runs-on: ubuntu-latest
    steps:

      - name: Download deployment artifact
        uses: actions/download-artifact@v8
        with:
          name: dragonfly_exe
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy test server
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |
          curl -X POST https://df-mc.dev/pullrequest \
            -H "X-API-Key: $API_KEY" \
            -F "pr=$PR_NUMBER" \
            -F "binary=@dragonfly_exe"

  cleanup:
    name: Cleanup
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete test server
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          curl -X DELETE "https://df-mc.dev/pullrequest/$PR_NUMBER" \
            -H "X-API-Key: $API_KEY"
